name: Frontend CI/CD

on:
  workflow_run:
    workflows: ["Backend CI/CD"]  # Name of your backend workflow
    types: [completed]
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/sydneykart-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            REACT_APP_PROD_BACKEND_URL=${{ secrets.REACT_APP_PROD_BACKEND_URL }}
            PUBLIC_URL=${{ secrets.PUBLIC_URL }}
            REACT_APP_PUBLIC_URL_PROD=${{ secrets.REACT_APP_PUBLIC_URL_PROD }}
            REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ${{ env.IMAGE_NAME }}:latest || exit 1

      - name: Delete Old Docker Container
        run: sudo docker rm -f sydneykart-frontend || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 4000:80 \
            --name sydneykart-frontend \
            --restart unless-stopped \
            -e REACT_APP_PROD_BACKEND_URL=${{ secrets.REACT_APP_PROD_BACKEND_URL }} \
            -e PUBLIC_URL=${{ secrets.PUBLIC_URL }} \
            -e REACT_APP_ENV=${{ secrets.REACT_APP_ENV }} \
            -e REACT_APP_PUBLIC_URL_PROD=${{ secrets.REACT_APP_PUBLIC_URL_PROD }} \
            ${{ env.IMAGE_NAME }}:latest